### ISSUE TITLE
Installs a bad version of easygui that stops inject_gba from being able to do anything.

### ISSUE THREAD

**Issue by Hking0036** [ajd4096/inject_gba#3]
The current version installs a bad version of easygui, so that when you attempt to run inject_gba you'll be greeted with a syntax error on file choice_box.py, line 76. it's a simple change from `Exception, e` to `Exception as e` and it's since been reflected on easygui's github page: robertlugg/easygui#107

**Comment by Hking0036** [comment]
Also on Lubuntu I get this error message:

`Traceback (most recent call last):
  File "/usr/local/bin/inject_gba", line 9, in <module>
    load_entry_point('inject-gba==0.1', 'console_scripts', 'inject_gba')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/inject_gba/inject_gba.py", line 9, in <module>
ImportError: No module named global_vars
`
